"""replace *_win with *_score columns

Revision ID: ff0753563bce
Revises:
Create Date: 2026-10-04 21:10:41.331980

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff0753563bce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_results", sa.Column("white_score", sa.Integer(), nullable=True))
    op.add_column("game_results", sa.Column("black_score", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE game_results SET white_score = white_wins * 100, black_score = black_wins * 100"
    )
    op.alter_column("game_results", "white_score", nullable=False)
    op.alter_column("game_results", "black_score", nullable=False)

    op.drop_column("game_results", "white_wins")
    op.drop_column("game_results", "black_wins")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_results", sa.Column("black_wins", sa.INTEGER(), nullable=True))
    op.add_column("game_results", sa.Column("white_wins", sa.INTEGER(), nullable=True))
    op.execute(
        "UPDATE game_results SET white_wins = white_score / 100, black_wins = black_score / 100"
    )

    op.drop_column("game_results", "black_score")
    op.drop_column("game_results", "white_score")
    # ### end Alembic commands ###
